"$schema" = "https://schemastore.netlify.app/netlify-toml.json?lol"

[build]
command = "deno task build"
publish = "dist/client"

[build.environment]
BUILDING = "true"

[dev]
command = "deno task dev"
targetPort = 3000

[dev.environment]
BUILDING = ""
